inherit_from: .rubocop_todo.yml

require:
  - rubocop-minitest

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  Exclude:
    - "vendor/**/*"

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 20

Minitest/MultipleAssertions:
  Enabled: false
